name: Check and Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Display contents of text1.txt
        run: cat text1.txt
      - name: Display contents of text2.txt
        run: cat text2.txt
      - name: Check for "Hello world" in files
        run: cat text1.txt text2.txt | grep -q 'Hello world'

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Display contents before packaging
        run: cat text1.txt text2.txt
      - name: Create compressed package
        run: cat text1.txt text2.txt | gzip > packaged.gz
      - name: Upload packaged artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged
          path: packaged.gz
